project:
  name: quickstart-discngine-3decision
  owner: quickstart-eng@amazon.com
  regions:
  - eu-central-1
  template: templates/discngine-3decision.template.yaml
  s3_regional_buckets: true
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
tests:
  new-vpc:
    regions:
      - eu-central-1
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      KeyPairName: quickstart-3dec
      TMPPassword: uX5#cRguB8LVGbO1gt-6
      EKSClusterName: test
      JWTPrivateKey: LS0
      JWTPublicKey: LS0
    template: templates/discngine-3decision.template.yaml