project:
  name: quickstart-discngine-3decision
  owner: quickstart-eng@amazon.com
  regions:
  - eu-central-1
  template: templates/discngine-3decision-main.template.yaml
  s3_regional_buckets: true
  parameters:
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
tests:
  new-vpc:
    regions:
      - eu-central-1
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      EKSClusterName: EKS-FQB6S2A0
      VPCID: vpc-0dde054ec72f963bf
      DBPassword: z94_MLvb_10_8
      DBSubnets: subnet-00243452b0baee610,subnet-07ee05732d16e138b,subnet-05f3d92923dd7f580
      TMPPassword: uX5#cRguB8LVGbO1gt-6
      KeyPairName: quickstart-3dec
      JWTPrivateKey: LS0
      JWTPublicKey: LS0
      NodeInstanceType: t3.medium
    template: templates/discngine-3decision-main.template.yaml
