// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Test the deployment
In order to test the deployment, get url and test


== Post-deployment steps
// If post-deployment steps are required, add them here. If not, remove the heading
=== Setup SSL certificates
3decision creates 2 Amazon Elastic Load Balancers. Both listen by default on port 80. 

- lb-3dec-node : this application load balancer serves the 3decision user UI. In order to add SLL, one solution is to create a new HTTPS listener on port 443 and add your certificate. In parallel you can will need to create a CNAME DNS entry in your DNS provider, pointing to the lb-3dec-node DNS name.

- lb-3dec-etl : this application load balancer serves the 3decision etl UI. This UI will only be used by admninistrators to add users or debug.
In order to add SLL, one solution is to create a new HTTPS listener on port 443 and add your certificate. In parallel you can will need to create a CNAME DNS entry in your DNS provider, pointing to the lb-3dec-etl DNS name.

//== Best practices for using {partner-product-short-name} on AWS


== Security
- 3decision will store your data in Amazon Oracle RDS and EBS volumes. In order to avoid any dataloss you should consider enabling backups for 3decision Amazon RDS and the EBS drives.
// Provide post-deployment best practices for using the technology on AWS, including considerations such as migrating data, backups, ensuring high performance, high availability, etc. Link to software documentation for detailed information.

