---
AWSTemplateFormatVersion: 2010-09-09
Description: "This template deploys the 3decision helm chart, as well as related helm and kubernetes resources. (qs-1s40771km)."
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Kubernetes and Helm Deployment"
  LintSpellExclude:
    - Discngine
    - 3decision

Parameters:
  TNamespace:
    Type: String
  RegistrySecretName:
    Type: String
  JWTSecretName:
    Type: String
  JWTPrivateKey:
    Type: String
    NoEcho: true
  JWTPublicKey:
    Type: String
  EKSClusterName:
    Type: String
  LoadBalancerEIP:
    Type: String
  TMPServer:
    Type: String
  TMPUsername:
    Type: String
  TMPPassword:
    Type: String
    NoEcho: true

Resources:
  IngressNginxNamespace:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: kube-system
      Manifest: |
        kind: Namespace
        apiVersion: v1
        metadata:
          name: ingress-nginx