---
AWSTemplateFormatVersion: 2010-09-09
Description: "This template deploys a Volume based on a public snapshot (qs-1s40771km)."
Metadata:
  QuickStartDocumentation:
    EntrypointName: "3decision EBS volume creation"
  LintSpellExclude:
    - Discngine
    - 3decision
Mappings: 
  RegionMap: 
    us-east-1:
      DataPub: snap-0f29d99587f056765	
      Choral: snap-0f4d129efcfaaf899
    eu-central-1:
      DataPub: snap-0b40f334750a4129a	
      Choral: snap-089f9b15de542ee74
Resources:
  DataPub:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs 
          Ref: 'AWS::Region'
      Encrypted: true
      SnapshotId: !FindInMap [RegionMap, !Ref "AWS::Region", DataPub]
  Choral:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: !Select 
        - 1
        - !GetAZs 
          Ref: 'AWS::Region'
      Encrypted: true
      SnapshotId: !FindInMap [RegionMap, !Ref "AWS::Region", Choral]
Outputs:
  DataPubVolumeID:
    Description: ID of the DataPub volume
    Value: !Ref DataPub
  ChoralVolumeID:
    Description: ID of the choral volume
    Value: !Ref Choral