---
AWSTemplateFormatVersion: 2010-09-09
Description: "This template deploys a Volume based on a public snapshot (qs-1s40771km)."
Metadata:
  QuickStartDocumentation:
    EntrypointName: "3decision EBS volume creation"
  LintSpellExclude:
    - Discngine
    - 3decision
Resources:
  Collection:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: !Select 
        - 2
        - !GetAZs 
          Ref: 'AWS::Region'
      SnapshotId: 'snap-067df9a89bef7a620'
  Data3Dec:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: !Select 
        - 2
        - !GetAZs 
          Ref: 'AWS::Region'
      SnapshotId: 'snap-0864d7a064ccaff25'
  Choral:
    Type: "AWS::EC2::Volume"
    Properties:
      AvailabilityZone: !Select 
        - 1
        - !GetAZs 
          Ref: 'AWS::Region'
      SnapshotId: 'snap-089f9b15de542ee74'
Outputs:
  CollectionVolumeID:
    Description: ID of the collection volume
    Value: !Ref Collection
  DataVolumeID:
    Description: ID of the data3dec volume
    Value: !Ref Data3Dec
  ChoralVolumeID:
    Description: ID of the choral volume
    Value: !Ref Choral