---
AWSTemplateFormatVersion: 2010-09-09
Description: "This template deploys the 3decision helm chart, as well as related helm and kubernetes resources. (qs-1s40771km)."
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Kubernetes and Helm Deployment"
  LintSpellExclude:
    - Discngine
    - 3decision
Parameters:
  TNamespace:
    Type: String
  JWTSecretName:
    Type: String
  JWTPrivateKey:
    Type: String
    NoEcho: true
  JWTPublicKey:
    Type: String
  EKSClusterName:
    Type: String
  DBPassword:
    Type: String
  DBConnectionString:
    Type: String
  CollectionVolumeID:
    Type: String
  Data3DecVolumeID:
    Type: String
##TO DELETE
  TMPServer:
    Type: String
  TMPUsername:
    Type: String
  TMPPassword:
    Type: String
    NoEcho: true
Resources:
  TDecisionNamespace:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: 'kube-system'
      Manifest: !Sub |
        kind: Namespace
        apiVersion: v1
        metadata:
          name: ${TNamespace}
  RabbitMQChart:
    Type: "AWSQS::Kubernetes::Helm"
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    Properties:
      ClusterID: !Ref EKSClusterName
      Name: rabbitmq
      Namespace: rabbitmq
      Repository: https://charts.bitnami.com/bitnami
      Chart: rabbitmq
      Version: 6.27.1
      Values:
        image.tag: 3.8.19-debian-10-r30
        rabbitmq.username: discngine
        rabbitmq.password: lapin79
  RegistryAccessSecret:
    Type: "AWSQS::Kubernetes::Resource"
    DependsOn: TDecisionNamespace
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: !Ref TNamespace
      Manifest: !Sub |
        kind: Secret
        apiVersion: v1
        type: kubernetes.io/dockerconfigjson
        metadata:
          name: ociregistry
          namespace: ${TNamespace}
        data:
          .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImZyYS5vY2lyLmlvIjogew0KICAgICAgImF1dGgiOiAiWkdselkyNW5hVzVsTVM5cFpHTnpYMlpsWkdWeVlYUnBiMjR2YW05dVlYUm9ZVzR1YldGdVlYTnpaVzVBWkdselkyNW5hVzVsTG1OdmJUcDFXRFVqWTFKbmRVSTRURlpIWWs4eFozUXROZz09Ig0KICAgIH0NCiAgfQ0KfQ0K
  JWTSecret:
    Type: "AWSQS::Kubernetes::Resource"
    DependsOn: TDecisionNamespace
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: !Ref TNamespace
      Manifest: !Sub |
        kind: Secret
        apiVersion: v1
        type: opaque
        metadata:
          name: ${JWTSecretName}
          namespace: ${TNamespace}
        data:
          id_rsa: ${JWTPrivateKey}
          id_rsa.pub: ${JWTPublicKey}
  TdecisionChart:
    Type: "AWSQS::Kubernetes::Helm"
    DependsOn: [ JWTSecret, RegistryAccessSecret, CertManagerChart ]
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    Properties:
      ClusterID: !Ref EKSClusterName
      Name: tdecision
      Namespace: !Ref TNamespace
      Chart: oci://751149478800.dkr.ecr.eu-central-1.amazonaws.com/3decision-private:latest
      RepositoryOptions:
        Username: !Ref TMPUsername
        Password: !Ref TMPPassword
      Values:
        nodeCloud.volumes.jwtSecret.name: !Ref JWTSecretName
        oracle.password: !Ref DBPassword
        oracle.connectionString: !Ref DBConnectionString
        pipelinePilot.volumes.data3dec.awsElasticBlockStore.volumeID: !Ref Data3DecVolumeID
        pipelinePilot.volumes.collection.awsElasticBlockStore.volumeID: !Ref CollectionVolumeID