---
AWSTemplateFormatVersion: 2010-09-09
Description: "This template deploys the 3decision helm chart, as well as related helm and kubernetes resources. (qs-1s40771km)."
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Kubernetes and Helm Deployment"
  LintSpellExclude:
    - Discngine
    - 3decision

Parameters:
  TNamespace:
    Type: String
  RegistrySecretName:
    Type: String
  JWTSecretName:
    Type: String
  JWTPrivateKey:
    Type: String
    NoEcho: true
  JWTPublicKey:
    Type: String
  EKSClusterName:
    Type: String
  LoadBalancerEIP:
    Type: String
  TMPServer:
    Type: String
  TMPUsername:
    Type: String
  TMPPassword:
    Type: String
    NoEcho: true
Resources:
  IngressNginxChart:
    Type: "AWSQS::Kubernetes::Helm"
    DependsOn: IngressNginxNamespace
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    Properties:
      ClusterID: !Ref EKSClusterName
      Name: ingress-nginx
      Namespace: ingress-nginx
      Repository: https://kubernetes.github.io/ingress-nginx
      Chart: ingress-nginx
      Values:
        controller.service.loadBalancerIP: !Ref LoadBalancerEIP
  CertManagerChart:
    Type: "AWSQS::Kubernetes::Helm"
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    Properties:
      ClusterID: !Ref EKSClusterName
      Name: cert-manager
      Namespace: cert-manager
      Repository: https://charts.jetstack.io
      Chart: cert-manager
      Version: 1.4.0
      Values:
        installCRDs: true
  CertManagerChart:
    Type: "AWSQS::Kubernetes::Helm"
    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
    Properties:
      ClusterID: !Ref EKSClusterName
      Name: rabbitmq
      Namespace: rabbitmq
      Repository: https://charts.bitnami.com/bitnami
      Chart: rabbitmq
      Version: 8.20.2
  TDecisionNamespace:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: 'kube-system'
      Manifest: !Sub |
        kind: Namespace
        apiVersion: v1
        metadata:
          name: ${TNamespace}
  RegistryAccessSecret:
    Type: "AWSQS::Kubernetes::Resource"
    DependsOn: TDecisionNamespace
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: !Ref TNamespace
      Manifest: !Sub |
        kind: Secret
        apiVersion: v1
        type: kubernetes.io/dockerconfigjson
        metadata:
          name = ${RegistrySecretName}
          namespace = ${TNamespace}
        data: |
          {
            "auths": {
              "${TMPServer}": {
                "auth": "base64encode("${TMPUsername}:${TMPPassword}")"
              }
            }
          }
  JWTSecret:
    Type: "AWSQS::Kubernetes::Resource"
    DependsOn: TDecisionNamespace
    Properties:
      ClusterName: !Ref EKSClusterName
      Namespace: !Ref TNamespace
      Manifest: !Sub |
        kind: Secret
        apiVersion: v1
        type: opaque
        metadata:
          name = ${JWTSecretName}
          namespace = ${TNamespace}
        data:
          id_rsa: ${JWTPrivateKey}
          id_rsa.pub: ${JWTPublicKey}
#  TdecisionChart:
#    Type: "AWSQS::Kubernetes::Helm"
#    Metadata: { cfn-lint: { config: { ignore_checks: [ E3012 ] } } }
#    Properties:
#      ClusterID: !Ref EKSClusterName
#      Name: tdecision
#      Namespace: !Ref TNamespace
#     Repository: 
#    Chart: 3decision
#   Version: 8.20.2