---
AWSTemplateFormatVersion: 2010-09-09
Description: "This template deploys a DNS record set to be used by the nginx-controller (qs-1s40771km)."
Metadata:
  QuickStartDocumentation:
    EntrypointName: "DNS Record Set creation"
  LintSpellExclude:
    - Discngine
    - 3decision

Parameters:
  HostedZoneId:
    type: String
  HostedZoneName:
    type: String

Resources:
  LoadBalancerEIP:
    Condition: NATGateways&PublicSubnets&PrivateSubnetsCondition
    DependsOn: VPCGatewayAttachment
    Type: AWS::EC2::EIP
    Properties:
      Tags:
        - Key: Name
          Value: LoadBalancerEIP
  DNSRecord3dec:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZoneID
      Name: !Join ['', ['3decision', ., !Ref 'HostedZone', .]]
      ResourceRecords:
      - !Ref LoadBalancerEIP
      TTL: 900
      Type: A
  DNSRecordPP:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZoneID
      Name: !Join ['', ['3decision-pp', ., !Ref 'HostedZone', .]]
      ResourceRecords:
      - !Ref LoadBalancerEIP
      TTL: 900
      Type: A
Outputs:
  LoadBalancerEIP:
    Value: !Ref LoadBalancerEIP