---
AWSTemplateFormatVersion: 2010-09-09
Description: "This template sets up Discngine 3decision infrastructure. (qs-1snm79fb4)."
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Parameters for launching into an existing Amazon EKS cluster"
  LintSpellExclude:
    - Discngine
    - 3decision
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Basic configuration
        Parameters:
          - EKSClusterName
          - VPCID
          - ConfigureEKS
      - Label:
          default: Discngine 3decision network configuration
        Parameters:
          - DomainName
          - HostedZoneId
          - CertificateArn
          - TdecRecordName
          - EtlRecordName
          - LoadBalancerType
      - Label:
          default : Discngine 3decision database configuration
        Parameters:
          - DBInstanceIdentifier
          - DBName
          - DBPassword
          - DBSubnets
          - DBInstanceClass
          - DBMultiZone
      - Label:
          default: Discngine 3decision Kubernetes configuration
        Parameters:
          - EtlUser
          - EtlPassword
          - TNamespace
          - JWTPrivateKey
          - JWTPublicKey
          - JWTKeysSecretName
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
      EKSClusterName:
        default: Name of EKS Cluster
      VPCID:
        default: ID of the VPC
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      DBInstanceIdentifier:
        default: Identifier of the database
      DBName:
        default: Name of the database
      DBPassword:
        default: Password of the database
      DBSubnets:
        default: Subnets in the database subnet group
      DBInstanceClass:
        default: Instance type of the database
      DBMultiZone:
        default: Database highly available
      TNamespace:
        default: 3decision Helm chart namespace
      JWTPrivateKey:
        default: Private SSH key in base 64 used for JWT
      JWTPublicKey:
        default: Public SSH key in base 64 used for JWT
      EtlUser:
        default: Username used for ETL
      EtlPassword:
        default: Password used for ETL
      ConfigureEKS:
        default: Configure Amazon EKS
      HostedZoneId:
        default: Route 53 hosted zone ID
      DomainName:
        default: Domain name used for load balancing
      CertificateArn:
        default: ARN of a certificate
      TdecRecordName:
        default: Record name of main 3decision page
      EtlRecordName:
        default: Record name of ETL page
      LoadBalancerType:
        default: Type of load balancer created
Parameters:
  EKSClusterName:
    Description: (Required) Name of the Amazon EKS cluster into which the stacks are deployed.
    Type: String
  VPCID:
    Type: String
    Description: (Required) ID of the VPC in which the Amazon EKS cluster is deployed.
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription:
      The Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a 
      hyphen (-).
    Default: aws-quickstart
    Description:
      Name of the S3 bucket for your copy of the Quick Start assets. 
      Keep the default name unless you are customizing the template. 
      Changing the name updates code references to point to a new Quick 
      Start location. This name can include numbers, lowercase letters, 
      uppercase letters, and hyphens, but do not start or end with a hyphen (-). 
      See https://aws-quickstart.github.io/option1.html.
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'AWS Region where the Quick Start S3 bucket (QSS3BucketName) is 
    hosted. Keep the default Region unless you are customizing the template. 
    Changing this Region updates code references to point to a new Quick Start location. 
    When using your own bucket, specify the Region. 
    See https://aws-quickstart.github.io/option1.html.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription:
      The Quick Start S3 key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slashes (/). The prefix should
      end with a forward slash (/).
    Default: quickstart-discngine-3decision/
    Description:
      S3 key prefix that is used to simulate a folder for your copy of the 
      Quick Start assets. Keep the default prefix unless you are customizing 
      the template. Changing this prefix updates code references to point to 
      a new Quick Start location. This prefix can include numbers, lowercase 
      letters, uppercase letters, hyphens (-), and forward slashes (/). End with 
      a forward slash. See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html 
      and https://aws-quickstart.github.io/option1.html.
    Type: String
  DBInstanceIdentifier:
    Default: db3dec
    Description: Database instance name. The default is db3dec.
    Type: String
    MinLength: '1'
    MaxLength: '8'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DBName:
    Default: ORCL
    Description: Amazon RDS Oracle database name. The default is ORCL.
    Type: String
    MinLength: '1'
    MaxLength: '8'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: true
    Description: Database administrator account password.
    Type: String
    MinLength: '8'
    MaxLength: '41'
  DBSubnets:
    Description: Subnets to use for the creation of the db subnet group. These must be the same subnets as the ones containing your Amazon EKS nodes.
    Type: CommaDelimitedList
  DBInstanceClass:
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium
      - db.t3.large
      - db.t3.xlarge
      - db.t3.2xlarge
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
    Default: db.t3.medium
    Description: Amazon RDS instance type for the Oracle Database instance. We recommend t3.xlarge for production.
    Type: String
  DBMultiZone:
    Description: High Availability (Multi-AZ) for Oracle RDS. For more information, refer to https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.MultiAZ.html.
    Type: String
    AllowedValues: [ 'true', 'false' ]
    Default: 'true'
  TNamespace:
    Default: tdecision
    Description: (Optional) Name of the Kubernetes namespace in which the 3decision helm chart will be deployed. This default to tdecision. The namespace will be created if it doesn't already exist.
    Type: String
  JWTKeysSecretName:
    Default: ""
    Description: The name of a secret in SecretsManager containing base64 keys in fields private_key and public_key. If used, you must disable wrapping and paste the base64 encoded strings that retrieve by running 'base64 -w0 id_rsa' and 'base64 -w0 id_rsa.pub'. By default, this will have no value, in which case the variables JWTPrivateKey and JWTPublicKey are used.
    Type: String
  JWTPrivateKey:
    Default: ""
    Description: SSH private key in base64 format. You must disable wrapping and paste the base64 encoded string that you can retrieve by running 'base64 -w0 id_rsa'. If JWTKeysSecretName is set, this variable is not used.
    Type: String
    NoEcho: true
  JWTPublicKey:
    Default: ""
    Description: SSH public key in base64 format. You must disable wrapping and paste the base64 encoded string that you can retrieve by running 'base64 -w0 id_rsa.pub'. If JWTKeysSecretName is set, this variable is not used.
    Type: String
  EtlUser:
    Default: "3decision"
    Description: 3decision username.
    Type: String
  EtlPassword:
    Description: 3decision password.
    Type: String
    NoEcho: true
  ConfigureEKS:
    Description: (Optional) Choose true to create resources for your EKS cluster that are specific to Amazon EKS Quick Start.
    Default: 'false'
    Type: String
    AllowedValues: ['true', 'false']
  NodeSecurityGroup:
    Description: (Optional) ID of the Amazon EKS security group in which to add the RDS ingress.
    Default: ''
    Type: String
  HostedZoneId:
    Default: ""
    Description: (Optional) Create DNS records for the Route 53 hosted zone.
    Type: String
  DomainName:
    Description: Root domain name used for load balancer rules. This is only the root domain name, not the FQDN (e.g., example.com).
    Type: String
  CertificateArn:
    Default: ""
    Description: (Optional) ARN of a certificate of the associated domain you want added to the load balancer.
    Type: String
  TdecRecordName:
    Default: "3decision"
    Description: Subpath of the main 3decision page. Will add route to hostedZone if given as recordName.domainName.
    Type: String
  EtlRecordName:
    Default: "3decision-etl"
    Description: Subpath of the 3decision ETL page. Will add route to hostedZone if given as recordName.domainName.
    Type: String
  LoadBalancerType:
    AllowedValues:
      - internet-facing
      - internal
    Default: "internal"
    Description: Type of load balancer created. This can either be internet-facing for a public load balancer or internal for private load balancers.
    Type: String

Rules:
  DiscngineSupportedRegionRule:
    Assertions:
      - Assert:
          Fn::Contains:
            - - us-east-1
              - eu-central-1
            - !Ref AWS::Region
        AssertDescription: The Quick Start is supported only in us-east-1 and eu-central-1 AWS Regions. Please contact Discngine to request support for other Regions.

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
  UseJWTKeysSecret: !Not [ !Equals [ "", !Ref JWTKeysSecretName ] ]
  ConfigureEKS: !Equals ['true', !Ref ConfigureEKS]
  ConfigureDNS: !Not [ !Equals [ "", !Ref HostedZoneId ] ]

Resources:
  EKSCluster:
    Type: AWS::CloudFormation::Stack
    Condition: ConfigureEKS
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-amazon-eks/templates/amazon-eks-entrypoint-existing-cluster.template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        VPCID: !Ref VPCID
        KubeClusterName: !Ref EKSClusterName
        QSS3BucketName: !Ref QSS3BucketName
        QSS3BucketRegion: !Ref QSS3BucketRegion
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
  EBSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/discngine-3decision-ebs.template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/discngine-3decision-oracle.template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        DBInstanceIdentifier: !Ref DBInstanceIdentifier
        DBName: !Ref DBName
        DBSubnets: !Join [ ",", !Ref DBSubnets ]
        DBInstanceClass: !Ref DBInstanceClass
        VpcId: !Ref VPCID
        NodeSecurityGroupId: !Ref NodeSecurityGroup
        DBMultiZone: !Ref DBMultiZone
  3decisionKubeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/discngine-3decision-kube.template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        TNamespace: !Ref TNamespace
        JWTPrivateKey: !If [UseJWTKeysSecret, !Sub '{{resolve:secretsmanager:${JWTKeysSecretName}:SecretString:private_key}}', !Ref JWTPrivateKey]
        JWTPublicKey: !If [UseJWTKeysSecret, !Sub '{{resolve:secretsmanager:${JWTKeysSecretName}:SecretString:public_key}}', !Ref JWTPublicKey]
        EKSClusterName: !Ref EKSClusterName
        DataVolumeID: !GetAtt EBSStack.Outputs.DataVolumeID
        CollectionVolumeID: !GetAtt EBSStack.Outputs.CollectionVolumeID
        DBConnectionString: !GetAtt RDSStack.Outputs.PrimaryConnectionString
        DBPassword: !Ref DBPassword
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
        EtlUser: !Ref EtlUser
        EtlPassword: !Ref EtlPassword
        TdecRecordName: !Ref TdecRecordName
        EtlRecordName: !Ref EtlRecordName
        LoadBalancerType: !Ref LoadBalancerType
  3decisionDNSStack:
    Type: AWS::CloudFormation::Stack
    Condition: ConfigureDNS
    DependsOn: 3decisionKubeStack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/discngine-3decision-dns.template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        HostedZoneId: !Ref HostedZoneId
        DomainName: !Ref DomainName
        TdecRecordName: !Ref TdecRecordName
        EtlRecordName: !Ref EtlRecordName